"use client";

import React, { useState, useEffect } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { KeyRound, ArrowRight, AlertCircle } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

export default function AdminMfaPage() {
  const router = useRouter();
  const [code, setCode] = useState("");
  const [challengeToken] = useState<string>(() => {
    if (typeof window !== "undefined") {
      return (
        new URLSearchParams(window.location.search).get("challenge") ||
        sessionStorage.getItem("mfa_challenge_token") ||
        ""
      );
    }
    return "";
  });
  const [email] = useState<string>(() => {
    if (typeof window !== "undefined") {
      return sessionStorage.getItem("mfa_email") || "";
    }
    return "";
  });
  const [isLoading, setIsLoading] = useState(false);
  const [errorMessage, setErrorMessage] = useState<string | null>(null);

  useEffect(() => {
    if (!challengeToken) {
      router.push("/admin/login");
    }
  }, [challengeToken, router]);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (code.length !== 6) {
      setErrorMessage("Please enter all 6 digits of your authenticator code.");
      return;
    }

    setIsLoading(true);
    setErrorMessage(null);

    try {
      const res = await fetch("/api/admin/auth/mfa/verify", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          challenge_token: challengeToken,
          code: code.trim(),
        }),
      });

      const data = await res.json();
      if (!res.ok || !data.success) {
        throw new Error(data.error || "MFA verification failed. Please try again.");
      }

      sessionStorage.removeItem("mfa_challenge_token");
      sessionStorage.removeItem("mfa_email");

      router.push("/admin");
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : "Verification failed";
      setErrorMessage(msg);
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="min-h-[80vh] flex flex-col justify-center items-center px-4 py-12">
      <div className="w-full max-w-md space-y-8">
        <div className="text-center space-y-2">
          <div className="w-12 h-12 rounded-2xl bg-amber-500 text-stone-900 flex items-center justify-center mx-auto shadow-md">
            <KeyRound className="w-6 h-6" />
          </div>
          <span className="text-[11px] font-bold uppercase tracking-widest text-[#b8860b]">
            Elevated Security Gate
          </span>
          <h1 className="font-serif text-3xl font-bold text-[#4a1220]">
            Two-Factor Challenge
          </h1>
          <p className="text-xs text-stone-500">
            Enter the 6-digit TOTP authentication code generated by your authenticator app for{" "}
            <strong className="text-stone-700">{email || "your account"}</strong>.
          </p>
        </div>

        <div className="p-8 rounded-3xl bg-white border border-[#e7dfd5] shadow-xs space-y-6">
          {errorMessage && (
            <div className="p-3 rounded-xl bg-red-50 border border-red-200 text-xs text-red-700 flex items-start gap-2">
              <AlertCircle className="w-4 h-4 shrink-0 mt-0.5 text-red-600" />
              <span>{errorMessage}</span>
            </div>
          )}

          <form onSubmit={handleSubmit} className="space-y-5">
            <div className="space-y-1">
              <label className="text-xs font-semibold text-stone-700 block text-center">
                6-Digit Security Code
              </label>
              <Input
                type="text"
                inputMode="numeric"
                maxLength={6}
                required
                autoFocus
                placeholder="123456"
                value={code}
                onChange={(e) => setCode(e.target.value.replace(/\D/g, ""))}
                className="text-center tracking-[0.5em] font-mono text-xl h-14 font-bold"
              />
              <span className="text-[10px] text-stone-400 block text-center">
                Demo code for Super Admin: <code className="font-bold text-[#6b1426]">123456</code>
              </span>
            </div>

            <Button
              type="submit"
              disabled={isLoading || code.length !== 6}
              className="w-full h-11 text-xs font-semibold flex items-center justify-center gap-2"
            >
              {isLoading ? "Verifying Token..." : "Confirm & Access Console"}
              <ArrowRight className="w-4 h-4 text-[#dfb15b]" />
            </Button>
          </form>

          <div className="pt-2 text-center">
            <Link
              href="/admin/login"
              className="text-xs text-stone-500 hover:text-[#6b1426] transition-colors"
            >
              Cancel and return to login
            </Link>
          </div>
        </div>
      </div>
    </div>
  );
}
